export const frases = [
    "La vida es lo que pasa mientras estás ocupado haciendo otros planes",
    "El único modo de hacer un gran trabajo es amar lo que haces",
    "No cuentes los días, haz que los días cuenten",
    "El éxito es aprender a ir de fracaso en fracaso sin desesperarse",
    "Haz de tu vida un sueño, y de tu sueño una realidad",
    "El mayor riesgo es no tomar ninguno",
    "La felicidad no es algo listo para usar. Viene de tus propias acciones",
    "No busques los errores, busca un remedio",
    "Nunca es demasiado tarde para ser lo que podrías haber sido",
    "Si puedes soñarlo, puedes hacerlo",
    "El genio es 1% inspiración y 99% transpiración",
    "La mejor manera de predecir el futuro es crearlo",
    "No tienes que ser grande para empezar, pero tienes que empezar para ser grande",
    "No dejes que el ruido de las opiniones ajenas apague tu propia voz interior",
    "Las oportunidades no ocurren, las creas",
    "El fracaso es solo la oportunidad de comenzar de nuevo, pero con más experiencia",
    "Todo parece imposible hasta que se hace",
    "No esperes. El tiempo nunca será el justo",
    "La disciplina es el puente entre las metas y los logros",
    "No es la especie más fuerte la que sobrevive, ni la más inteligente, sino la que mejor se adapta al cambio",
    "El talento gana juegos, pero el trabajo en equipo y la inteligencia ganan campeonatos",
    "Lo único imposible es aquello que no intentas",
    "Cuando pierdas, no pierdas la lección",
    "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso",
    "El que tiene un porqué para vivir puede soportar casi cualquier cómo",
    "Sueña en grande y atrévete a fallar",
    "El éxito es la suma de pequeños esfuerzos repetidos día tras día",
    "El mayor error que puedes cometer en la vida es temer continuamente que vas a cometer uno",
    "Lo que obtienes al lograr tus metas no es tan importante como en lo que te conviertes al lograrlas"
];

